### ISSUE TITLE
Instruction on using SASS instead of Rebass

### ISSUE THREAD

**Issue by faahim** [kripod/gatsby-starter-modern#5]
Hi!

Thanks for the amazing starter pack, this is my favorite so far!

I just found out that you've updated it to use Rebass instead of SASS for styling. But I prefer SASS and it's what my project requires. I'm relatively new to this. Could you please guide me to any instruction or something to understand how I could replace Rebass with SASS?
Thanks! :slightly_smiling_face:

**Comment by kripod** [comment]
I guess I should create a separate branch for the SASS version, but I’m not syet ure how it could be fetched with the `gatsby new` command.

Anyway, if you’re interested in maintaining design systems with ease, you should definitely check out the links in the readme’s style management section.

**Comment by kripod** [comment]
I just [created a new branch](https://github.com/kripod/gatsby-starter-modern/tree/scss) with instructions about cloning it using `gatsby-cli`: Please use `gatsby new gatsby-example-site https://github.com/kripod/gatsby-starter-modern#scss`
